version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: smoke-monitoring-app
    ports:
      - "3001:80"  # Maps port 80 in the container to port 3001 on the host
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge