name: CI/CD Pipeline

on:
  push:
    branches:
      - register

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smk-front:latest -f Frontend/Dockerfile Frontend/

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smk-front:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Run this job after the build job

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          debug: true
          script: |
            cd /home/moji/smk
            docker-compose pull
            docker-compose up -d
